project:
  type: book
  output-dir: ../docs
book:
  title: Компьютерный анализ текста
  author: Ольга Алиева
  date: today
  abstract: Курс для магистерской программы НИУ ВШЭ 'Цифровые методы в гуманитарных
    науках' (2024/2025). <br><br> Призер конкурса [DH Awards 2024](http://dhawards.org/dhawards2024/results/) в рубрике BEST DH TRAINING MATERIALS. <br><br> ![](images/DHAwards2024-trainingMaterials)
  chapters:
  - index.qmd
  - 01_start.qmd
  - tabular.qmd
  - plot.qmd
  - iterate.qmd
  - import.qmd
  - share.qmd
  - regex.qmd
  - scrape.qmd
  - tokenize.qmd
  - count.qmd
  - sentiment.qmd
  - lsa.qmd
  - pmi.qmd
  - lda.qmd
  - cluster.qmd
  - stylo.qmd
  - consensus.qmd
  - igraph.qmd
  - ggraph.qmd
  - dracor.qmd
  - maps.qmd
  - regression.qmd
  - multivar.qmd
  - classification.qmd
  - multiclass.qmd
  - dnn.qmd
  - shiny.qmd
  - references.qmd
bibliography: references.bib
language: custom.yml
lang: ru
df-print: paged
format:
  html:
    theme: cosmo
    css: include/webex.css
    include-after-body: include/webex.js
prefer-html: true