project:
  type: book
  output-dir: ../docs

book:
  title: "Компьютерный анализ текста"
  author: "Ольга Алиева"
  date: today
  abstract: "Курс для магистерской программы НИУ ВШЭ 'Цифровые методы в гуманитарных науках' (2024/2025)"
  chapters:
    - index.qmd
    - start.qmd
    - tabular.qmd
    - plot.qmd
    - iterate.qmd
    - import.qmd
    - share.qmd
    - regex.qmd
    - scrape.qmd
    - references.qmd
  

bibliography: references.bib
language: custom.yml
lang: ru
df-print: paged

format:
  html:
    theme: cosmo
   
      
  pdf:
    documentclass: scrreprt



