# Введение {.unnumbered}

## Об этом курсе
Этот сайт содержит материалы к курсу "Компьютерный анализ текста в R" для магистерской программы НИУ ВШЭ "[Цифровые методы в гуманитарных науках](https://www.hse.ru/ma/dh/)". Предыдущую версию курса можно найти [здесь](https://locusclassicus.github.io/text_analysis_2023/). 

И тексты, и инструменты для работы с ними подобраны таким образом, чтобы помочь студентам гуманитарных специальностей (филологам, философам, историкам и др.) как можно быстрее, _но с полным пониманием дела_ перейти к применению количественных методов в собственной работе. 

Чтобы лучше понимать, какие из этих методов более всего востребованы в научной работе, преподаватели магистратуры "Цифровые методы в гуманитарных науках" -- Б.В. Орехов, А.А. Осмоловская и О.В. Алиева -- организовали в 2024 г. серию встреч с ведущими представителями отрасли. Видео этих встреч и литературу к семинарам можно найти на сайте <http://criticaldh.ru/>.  

Там мы собрали именно _теоретические_ обсуждения и литературу к ним, а в этом курсе предлагаем приступить к _практике_ DH (на языке R). Оба этих аспекта, в нашем представлении и в программе магистратуры тесно связаны: одного программирования не хватит, чтобы стать "цифровым гуманистом", а теории недостаточно, чтобы судить об успешности тех или иных цифровых проектов. Поэтому этот курс старается стоять на двух ногах и соединять кодинг с теоретической рефлексией. Это почти невыполнимая задача ~~но когда нам это мешало~~. 

## Ресурсы

И в теоретическом, и в практическом плане курс опирается на огромную работу, уже проделанную преподавателями магистратуры ЦМГН. Важнейшие наши достижения собрал Б.В. Орехов: <https://github.com/nevmenandr/awesome-dh-hse>. Здесь вы найдете ссылки на видео, научно-популярные и научные публикации и датасеты.

Если вдруг вам не хватит практических заданий по R, то в качестве дополнения к оффлайн-курсу можно рекомендовать онлайн-курс Георгия Мороза "[Введение в анализ данных на R для гуманитарных и социальных наук](https://openedu.ru/course/hse/IDAR/)". К этому курсу прилагается онлайн-ноутбук (<https://agricolamz.github.io/daR4hs/>) с комментариями и всем кодом, и он полностью открыт. Надо иметь в виду, однако, что онлайн-курс рассчитан всего на 9 недель, в то время как наш -- на два семестра, так что его можно использовать лишь как вспомогательный ресурс, но не замену.

## Программа

Курс 2024/2025 г. включает в себя три основных блока и 24 темы. Программа носит предварительный характер и может быть чуть изменена.

**Часть 1. Основы работы в R**

1. Знакомство с R и RStudio. Начало работы. Объекты, функции, операторы. 
2. Визуализация данных: базовый R, lattice, ggplot2.
3. Трансформация данных. «Опрятные» данные с dplyr и tidyverse. 
4. Условия и циклы. Написание собственных функций. Итерации с purrr.
5. Импорт данных. Импорт данных из XML.
6. Воспроизводимые исследования. RMarkdown. Quarto.
7. Регулярные выражения: базовый R и stringr.
8. HTML. Веб-скрапинг.

**Часть 2. Методы анализа текста**

9. Токенизация. Морфологический и синтаксический анализ. 
10. Распределения слов и анализ частотностей. 
11. Анализ эмоциональной тональности (метод словарей). 
12. Векторные представления слов. LSA.
13. Векторные представления слов. PMI, Word2Vec.
14. Тематическое моделирование (LDA). 
15. Анализ текста с помощью сетей (графов). 
16. Описание и анализ графов. 

**Часть 3. Статистика и машинное обучение**

17. Обучение без учителя: кластеризация.
18. Простая и множественная линейная регрессия. 
19. Алгоритмы для бинарной и многоклассовой классификации.  
20. Деревья решений и правил. Бэггинг, случайные леса, бустинг.
21. Протоколы проверки моделей. Проблема переобучения.
22. Конструирование признаков. Методы снижения размерности.
23. Методы “черного ящика”: опорные векторы.
24. Глубокое обучение.

## Оценивание

Домашние задания выполняются в GitHub Classroom. Еженедельно выполняются небольшие задания, которые оцениваются по бинарной шкале (1/0), раз в месяц -- консолидирующие задания на весь пройденный материал (оценка 0-10). Все необходимые ссылки вы найдете в чате курса в Telegram.

## Благодарности

За помощь в разработке курса и подготовке датасетов к нему автор благодарит Георгия Мороза и Бориса Орехова. Идеей количественного сравнения британских эмпириков в десятой главе я обязана своей коллеге по Школе философии и культурологии НИУ ВШЭ Дарье Дроздовой.

## Обратная связь

Если вы заметили ошибку или опечатку, можно писать на адрес [oalieva\@hse.ru](mailto:oalieva@hse.ru){.email}.
